sudo: required

language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/sd-agent
    - vendor/cache

python:
  - "2.7"

git:
  depth: 3

services:
  - docker

matrix:
  fast_finish: true

jobs:
  include:
    - stage: test csv
      install: gem install csvlint
      script: for metadata in `ls */metadata.csv`; do csvlint ${metadata}; done
